language: python
python:
- 3.6
services:
- docker
install:
- docker build -t max-object-detector .
- docker run -it -d -p 5000:5000 max-object-detector
- sleep 30
before_script:
- pip install flake8 pytest requests
script:
- flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
- pytest tests/test.py
