language: python
python:
- 3.6
services:
- docker
install:
- docker build -t max-object-detector .
- docker run -it -d -p 5000:5000 max-object-detector
- sleep 30
before_script:
- pip install flake8 pytest requests
script:
- flake8 . --max-line-length=127
- pytest tests/test.py
