name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
          python-version: 3.7

    - name: Build the Docker image
      run: docker build -f Dockerfile.arm32v7 -t max-object-detector:arm .

    - name: Run the Docker image
      run: docker run -it --rm -d -p 5000:5000 max-object-detector:arm

    - name: Install dependencies
      run: pip install -r requirements-test.txt

    - name: Lint with flake8
      run: flake8 . --max-line-length=127 --exclude utils/,protos/,training/training_code/

    - name: Wait for container to get ready
      run: sleep 30

    - name: Test with pytest
      run: pytest tests/test.py
